name: Triage New Pull Request
on: pull_request

jobs:

  triage:
    name: Triage
    runs-on: ubuntu-18.04
    steps:

    - name: Label
      uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
